version: '3.3'

services:

  application:
    image:
      pdf-generation-image
    container_name:
      pdf-generation-container
    ports:
      - 80:80
    depends_on:
      - database
      - redis
      - rabbitmq3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/pdf_generator
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234567
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6380
      - SPRING_RABBITMQ_HOST=rabbitmq3
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  database:
    image:
      postgres
    container_name:
      database
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: pdf_generator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  redis:
    image:
      redis-fsync
    container_name:
      redis
    ports:
      - 6380:6380
    volumes:
      - redis-volume:/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  rabbitmq3:
    image:
      rabbitmq:3.6-management
    container_name:
      rabbitmq-container
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  pgdata:
    external: true
  redis-volume:
    external: true


